# Generated by Django 6.0 on 2025-12-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='emission_factor',
            field=models.FloatField(help_text='kg CO₂ per unit'),
        ),
    ]
